services:
  minio:
    image: astrovela-minio-test:RELEASE.2025-07-23T15-54-02Z
    pull_policy: never
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:9000/minio/health/ready"]
  createbuckets:
    image: astrovela-mc-test:RELEASE.2025-08-13T08-35-41Z
    pull_policy: never
