name: Vane extension

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vane-native:
    uses: AstroVela/vane-extension-ci-tools/.github/workflows/_vane_extension_ci.yml@73f26ed76b625270c1f6e9d2f5b0ac47a55cfe72
    with:
      ci_tools_version: 73f26ed76b625270c1f6e9d2f5b0ac47a55cfe72
      manifest: vane-extension.toml
      build_jobs: 8
      run_native_tests: true
