name: Vane integration

on:
  pull_request:
  push:
    branches:
      - "vane/**"
      - v1.5-variegata
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  native:
    uses: AstroVela/vane-extension-ci-tools/.github/workflows/_vane_extension_ci.yml@2e8b13eacc65d496333c96f1c27ca1be0a78faf9
    with:
      ci_tools_version: 2e8b13eacc65d496333c96f1c27ca1be0a78faf9
      manifest: vane-extension.toml
      build_jobs: 4
      run_native_tests: true
